// QuestionsData.js
const questionsData = [
  {
    id: 0,
    question: "What is the capital of France?",
    options: ["Berlin", "London", "Paris", "Madrid"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 1,
    question: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 2,
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
    correctAnswerIndex: 3,
    disabled: false,
  },
  {
    id: 3,
    question: "Who wrote 'Romeo and Juliet'?",
    options: ["Charles Dickens", "William Shakespeare", "Leo Tolstoy", "Mark Twain"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 4,
    question: "What is the boiling point of water at sea level?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 5,
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 6,
    question: "How many continents are there on Earth?",
    options: ["5", "6", "7", "8"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 7,
    question: "Which is the largest mammal?",
    options: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 8,
    question: "Which language has the most native speakers?",
    options: ["English", "Mandarin Chinese", "Hindi", "Spanish"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 9,
    question: "Which country is known as the Land of the Rising Sun?",
    options: ["China", "Thailand", "Japan", "Vietnam"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 10,
    question: "Who painted the Mona Lisa?",
    options: ["Michelangelo", "Vincent Van Gogh", "Pablo Picasso", "Leonardo da Vinci"],
    correctAnswerIndex: 3,
    disabled: false,
  },
  {
    id: 11,
    question: "Which element has the chemical symbol 'O'?",
    options: ["Osmium", "Oxygen", "Gold", "Iron"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 12,
    question: "What is the smallest prime number?",
    options: ["0", "1", "2", "3"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 13,
    question: "Which country hosted the 2016 Summer Olympics?",
    options: ["China", "Brazil", "UK", "Russia"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 14,
    question: "Who is the author of 'Harry Potter'?",
    options: ["J.R.R. Tolkien", "J.K. Rowling", "Stephen King", "C.S. Lewis"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 15,
    question: "Which planet has the most moons?",
    options: ["Earth", "Mars", "Saturn", "Jupiter"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 16,
    question: "What is the hardest natural substance on Earth?",
    options: ["Gold", "Iron", "Diamond", "Quartz"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 17,
    question: "Which scientist developed the theory of relativity?",
    options: ["Isaac Newton", "Albert Einstein", "Nikola Tesla", "Galileo Galilei"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 18,
    question: "Which vitamin is produced when a person is exposed to sunlight?",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
    correctAnswerIndex: 3,
    disabled: false,
  },
  {
    id: 19,
    question: "Who was the first person to walk on the Moon?",
    options: ["Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong", "Michael Collins"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 20,
    question: "What is the main ingredient in traditional Japanese miso soup?",
    options: ["Seaweed", "Tofu", "Miso paste", "Rice"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 21,
    question: "Which country invented paper?",
    options: ["Egypt", "China", "Greece", "India"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 22,
    question: "Which instrument measures atmospheric pressure?",
    options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 23,
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"],
    correctAnswerIndex: 2,
    disabled: false,
  },
  {
    id: 24,
    question: "Which war ended with the Treaty of Versailles?",
    options: ["World War I", "World War II", "Korean War", "Vietnam War"],
    correctAnswerIndex: 0,
    disabled: false,
  },
  {
    id: 25,
    question: "What is the currency of Switzerland?",
    options: ["Euro", "Franc", "Pound", "Dollar"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 26,
    question: "Which is the longest river in the world?",
    options: ["Amazon", "Yangtze", "Mississippi", "Nile"],
    correctAnswerIndex: 3,
    disabled: false,
  },
  {
    id: 27,
    question: "Who discovered penicillin?",
    options: ["Louis Pasteur", "Alexander Fleming", "Marie Curie", "Gregor Mendel"],
    correctAnswerIndex: 1,
    disabled: false,
  },
  {
    id: 28,
    question: "What does DNA stand for?",
    options: [
      "Deoxyribonucleic Acid",
      "Dinucleic Acid",
      "Ribonucleic Acid",
      "Double Helix Acid"
    ],
    correctAnswerIndex: 0,
    disabled: false,
  },
  {
    id: 29,
    question: "Which city is known as the Silicon Valley of India?",
    options: ["Mumbai", "Hyderabad", "Bangalore", "Delhi"],
    correctAnswerIndex: 2,
    disabled: false,
  },
];

export default questionsData;
